"""add work order query index

Revision ID: 20260814_01
Revises: 20260810_01
Create Date: 2026-08-14 22:37:57.833255

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20260814_01"
down_revision: str | Sequence[str] | None = "20260810_01"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_work_orders_owner_status_id",
        "work_orders",
        ["owner_id", "status", "id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_work_orders_owner_status_id", table_name="work_orders")
    # ### end Alembic commands ###
